package net.minecraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAkrisaeMace extends ModelBase
{
  //fields
    ModelRenderer Shaft;
    ModelRenderer TopRung;
    ModelRenderer MiddleRung;
    ModelRenderer BottomRung;
    ModelRenderer BLeftSupport;
    ModelRenderer BRightSupport;
    ModelRenderer BFrontSupport;
    ModelRenderer BBackSupport;
    ModelRenderer MLeftSupport;
    ModelRenderer MRightSupport;
    ModelRenderer MBackSupport;
    ModelRenderer MFrontSupport;
    ModelRenderer TBackSupport;
    ModelRenderer TFrontSupport;
    ModelRenderer TRightSupport;
    ModelRenderer TLeftSupport;
    ModelRenderer TopCover;
    ModelRenderer TopZAxis;
    ModelRenderer TopXAxis;
    ModelRenderer GreenCube;
    ModelRenderer BRightSpike;
    ModelRenderer BLeftSpike;
    ModelRenderer BBackSpike;
    ModelRenderer BFrontSpike;
    ModelRenderer MLeftSpike;
    ModelRenderer MRightSpike;
    ModelRenderer MBackSpike;
    ModelRenderer MFrontSpike;
    ModelRenderer TLeftSpike;
    ModelRenderer TRightSpike;
    ModelRenderer TBackSpike;
    ModelRenderer TFrontSpike;
    ModelRenderer TopFrontSpike;
    ModelRenderer TopBackSpike;
    ModelRenderer TopLeftSpike;
    ModelRenderer TopRightSpike;
  
  public ModelAkrisaeMace()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shaft = new ModelRenderer(this, 2, 18);
      Shaft.addBox(0F, 0F, 0F, 1, 12, 1);
      Shaft.setRotationPoint(0F, -1F, 0F);
      Shaft.setTextureSize(64, 32);
      Shaft.mirror = true;
      setRotation(Shaft, 0F, 0F, 0F);
      TopRung = new ModelRenderer(this, 1, 14);
      TopRung.addBox(-0.5F, 0F, -0.5F, 2, 1, 2);
      TopRung.setRotationPoint(0F, 0F, 0F);
      TopRung.setTextureSize(64, 32);
      TopRung.mirror = true;
      setRotation(TopRung, 0F, 0F, 0F);
      MiddleRung = new ModelRenderer(this, 1, 14);
      MiddleRung.addBox(-0.5F, 0F, -0.5F, 2, 1, 2);
      MiddleRung.setRotationPoint(0F, 2F, 0F);
      MiddleRung.setTextureSize(64, 32);
      MiddleRung.mirror = true;
      setRotation(MiddleRung, 0F, 0F, 0F);
      BottomRung = new ModelRenderer(this, 1, 14);
      BottomRung.addBox(-0.5F, 0F, -0.5F, 2, 1, 2);
      BottomRung.setRotationPoint(0F, 4F, 0F);
      BottomRung.setTextureSize(64, 32);
      BottomRung.mirror = true;
      setRotation(BottomRung, 0F, 0F, 0F);
      BLeftSupport = new ModelRenderer(this, 3, 8);
      BLeftSupport.addBox(-0.5F, -4F, -0.5F, 1, 4, 1);
      BLeftSupport.setRotationPoint(1F, 0F, 0.5F);
      BLeftSupport.setTextureSize(64, 32);
      BLeftSupport.mirror = true;
      setRotation(BLeftSupport, 0F, 0F, 0.6981317F);
      BRightSupport = new ModelRenderer(this, 3, 8);
      BRightSupport.addBox(-0.5F, -4F, -0.5F, 1, 4, 1);
      BRightSupport.setRotationPoint(0F, 0F, 0.5F);
      BRightSupport.setTextureSize(64, 32);
      BRightSupport.mirror = true;
      setRotation(BRightSupport, 0F, 0F, -0.6981317F);
      BFrontSupport = new ModelRenderer(this, 3, 8);
      BFrontSupport.addBox(-0.5F, -4F, -0.5F, 1, 4, 1);
      BFrontSupport.setRotationPoint(0.5F, 0F, 0F);
      BFrontSupport.setTextureSize(64, 32);
      BFrontSupport.mirror = true;
      setRotation(BFrontSupport, 0.6981317F, 0F, 0F);
      BBackSupport = new ModelRenderer(this, 3, 8);
      BBackSupport.addBox(-0.5F, -4F, -0.5F, 1, 4, 1);
      BBackSupport.setRotationPoint(0.5F, 0F, 1F);
      BBackSupport.setTextureSize(64, 32);
      BBackSupport.mirror = true;
      setRotation(BBackSupport, -0.6981317F, 0F, 0F);
      MLeftSupport = new ModelRenderer(this, 8, 9);
      MLeftSupport.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      MLeftSupport.setRotationPoint(3.4F, -4.8F, 0.5F);
      MLeftSupport.setTextureSize(64, 32);
      MLeftSupport.mirror = true;
      setRotation(MLeftSupport, 0F, 0F, 0F);
      MRightSupport = new ModelRenderer(this, 8, 9);
      MRightSupport.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      MRightSupport.setRotationPoint(-2.4F, -4.8F, 0.5F);
      MRightSupport.setTextureSize(64, 32);
      MRightSupport.mirror = true;
      setRotation(MRightSupport, 0F, 0F, 0F);
      MBackSupport = new ModelRenderer(this, 8, 9);
      MBackSupport.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      MBackSupport.setRotationPoint(0.5F, -4.8F, 3.4F);
      MBackSupport.setTextureSize(64, 32);
      MBackSupport.mirror = true;
      setRotation(MBackSupport, 0F, 0F, 0F);
      MFrontSupport = new ModelRenderer(this, 8, 9);
      MFrontSupport.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      MFrontSupport.setRotationPoint(0.5F, -4.8F, -2.4F);
      MFrontSupport.setTextureSize(64, 32);
      MFrontSupport.mirror = true;
      setRotation(MFrontSupport, 0F, 0F, 0F);
      TBackSupport = new ModelRenderer(this, 14, 9);
      TBackSupport.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      TBackSupport.setRotationPoint(0.5F, -6.3F, 2.5F);
      TBackSupport.setTextureSize(64, 32);
      TBackSupport.mirror = true;
      setRotation(TBackSupport, 0.5061455F, 0F, 0F);
      TFrontSupport = new ModelRenderer(this, 14, 9);
      TFrontSupport.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      TFrontSupport.setRotationPoint(0.5F, -6.3F, -1.5F);
      TFrontSupport.setTextureSize(64, 32);
      TFrontSupport.mirror = true;
      setRotation(TFrontSupport, -0.5061455F, 0F, 0F);
      TRightSupport = new ModelRenderer(this, 14, 9);
      TRightSupport.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      TRightSupport.setRotationPoint(-1.5F, -6.3F, 0.5F);
      TRightSupport.setTextureSize(64, 32);
      TRightSupport.mirror = true;
      setRotation(TRightSupport, 0F, 0F, 0.5061455F);
      TLeftSupport = new ModelRenderer(this, 14, 9);
      TLeftSupport.addBox(-0.5F, 0F, -0.5F, 1, 2, 1);
      TLeftSupport.setRotationPoint(2.5F, -6.3F, 0.5F);
      TLeftSupport.setTextureSize(64, 32);
      TLeftSupport.mirror = true;
      setRotation(TLeftSupport, 0F, 0F, -0.5061455F);
      TopCover = new ModelRenderer(this, 3, 2);
      TopCover.addBox(-2F, 0F, -2F, 4, 1, 4);
      TopCover.setRotationPoint(0.5F, -7F, 0.5F);
      TopCover.setTextureSize(64, 32);
      TopCover.mirror = true;
      setRotation(TopCover, 0F, 0F, 0F);
      TopZAxis = new ModelRenderer(this, 21, 2);
      TopZAxis.addBox(0F, 0F, 0F, 1, 1, 3);
      TopZAxis.setRotationPoint(0F, -7.3F, -1F);
      TopZAxis.setTextureSize(64, 32);
      TopZAxis.mirror = true;
      setRotation(TopZAxis, 0F, 0F, 0F);
      TopXAxis = new ModelRenderer(this, 21, 9);
      TopXAxis.addBox(0F, 0F, 0F, 3, 1, 1);
      TopXAxis.setRotationPoint(-1F, -7.3F, 0F);
      TopXAxis.setTextureSize(64, 32);
      TopXAxis.mirror = true;
      setRotation(TopXAxis, 0F, 0F, 0F);
      GreenCube = new ModelRenderer(this, 10, 18);
      GreenCube.addBox(-1.5F, -5.5F, -1.5F, 3, 3, 3);
      GreenCube.setRotationPoint(0.5F, 0F, 0.5F);
      GreenCube.setTextureSize(64, 32);
      GreenCube.mirror = true;
      setRotation(GreenCube, 0F, 0F, 0F);
      BRightSpike = new ModelRenderer(this, 15, 25);
      BRightSpike.addBox(-1.5F, 0F, -0.5F, 1, 1, 1);
      BRightSpike.setRotationPoint(-1F, -1F, 0.5F);
      BRightSpike.setTextureSize(64, 32);
      BRightSpike.mirror = true;
      setRotation(BRightSpike, 0F, 0F, 0.6981317F);
      BLeftSpike = new ModelRenderer(this, 15, 25);
      BLeftSpike.addBox(0.5F, 0F, -0.5F, 1, 1, 1);
      BLeftSpike.setRotationPoint(2F, -1F, 0.5F);
      BLeftSpike.setTextureSize(64, 32);
      BLeftSpike.mirror = true;
      setRotation(BLeftSpike, 0F, 0F, -0.6981317F);
      BBackSpike = new ModelRenderer(this, 15, 25);
      BBackSpike.addBox(-0.5F, 0F, 0.5F, 1, 1, 1);
      BBackSpike.setRotationPoint(0.5F, -1F, 2F);
      BBackSpike.setTextureSize(64, 32);
      BBackSpike.mirror = true;
      setRotation(BBackSpike, 0.6981317F, 0F, 0F);
      BFrontSpike = new ModelRenderer(this, 15, 25);
      BFrontSpike.addBox(-0.5F, 0F, -1.5F, 1, 1, 1);
      BFrontSpike.setRotationPoint(0.5F, -1F, -1F);
      BFrontSpike.setTextureSize(64, 32);
      BFrontSpike.mirror = true;
      setRotation(BFrontSpike, -0.6981317F, 0F, 0F);
      MLeftSpike = new ModelRenderer(this, 15, 25);
      MLeftSpike.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      MLeftSpike.setRotationPoint(4.4F, -4.3F, 0.5F);
      MLeftSpike.setTextureSize(64, 32);
      MLeftSpike.mirror = true;
      setRotation(MLeftSpike, 0F, 0F, 0F);
      MRightSpike = new ModelRenderer(this, 15, 25);
      MRightSpike.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      MRightSpike.setRotationPoint(-3.4F, -4.3F, 0.5F);
      MRightSpike.setTextureSize(64, 32);
      MRightSpike.mirror = true;
      setRotation(MRightSpike, 0F, 0F, 0F);
      MBackSpike = new ModelRenderer(this, 15, 25);
      MBackSpike.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      MBackSpike.setRotationPoint(0.5F, -4.3F, 4.4F);
      MBackSpike.setTextureSize(64, 32);
      MBackSpike.mirror = true;
      setRotation(MBackSpike, 0F, 0F, 0F);
      MFrontSpike = new ModelRenderer(this, 15, 25);
      MFrontSpike.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      MFrontSpike.setRotationPoint(0.5F, -4.3F, -3.4F);
      MFrontSpike.setTextureSize(64, 32);
      MFrontSpike.mirror = true;
      setRotation(MFrontSpike, 0F, 0F, 0F);
      TLeftSpike = new ModelRenderer(this, 15, 25);
      TLeftSpike.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      TLeftSpike.setRotationPoint(4F, -5.3F, 0.5F);
      TLeftSpike.setTextureSize(64, 32);
      TLeftSpike.mirror = true;
      setRotation(TLeftSpike, 0F, 0F, -0.5061455F);
      TRightSpike = new ModelRenderer(this, 15, 25);
      TRightSpike.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      TRightSpike.setRotationPoint(-3F, -5.3F, 0.5F);
      TRightSpike.setTextureSize(64, 32);
      TRightSpike.mirror = true;
      setRotation(TRightSpike, 0F, 0F, 0.5061455F);
      TBackSpike = new ModelRenderer(this, 15, 25);
      TBackSpike.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      TBackSpike.setRotationPoint(0.5F, -5.3F, 4F);
      TBackSpike.setTextureSize(64, 32);
      TBackSpike.mirror = true;
      setRotation(TBackSpike, 0.5061455F, 0F, 0F);
      TFrontSpike = new ModelRenderer(this, 15, 25);
      TFrontSpike.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      TFrontSpike.setRotationPoint(0.5F, -5.3F, -3F);
      TFrontSpike.setTextureSize(64, 32);
      TFrontSpike.mirror = true;
      setRotation(TFrontSpike, -0.5061455F, 0F, 0F);
      TopFrontSpike = new ModelRenderer(this, 15, 25);
      TopFrontSpike.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      TopFrontSpike.setRotationPoint(0.5F, -7F, -1F);
      TopFrontSpike.setTextureSize(64, 32);
      TopFrontSpike.mirror = true;
      setRotation(TopFrontSpike, 0.3490659F, 0F, 0F);
      TopBackSpike = new ModelRenderer(this, 15, 25);
      TopBackSpike.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      TopBackSpike.setRotationPoint(0.5F, -7F, 2F);
      TopBackSpike.setTextureSize(64, 32);
      TopBackSpike.mirror = true;
      setRotation(TopBackSpike, -0.3490659F, 0F, 0F);
      TopLeftSpike = new ModelRenderer(this, 15, 25);
      TopLeftSpike.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      TopLeftSpike.setRotationPoint(2F, -7F, 0.5F);
      TopLeftSpike.setTextureSize(64, 32);
      TopLeftSpike.mirror = true;
      setRotation(TopLeftSpike, 0F, 0F, 0.3490659F);
      TopRightSpike = new ModelRenderer(this, 15, 25);
      TopRightSpike.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      TopRightSpike.setRotationPoint(-1F, -7F, 0.5F);
      TopRightSpike.setTextureSize(64, 32);
      TopRightSpike.mirror = true;
      setRotation(TopRightSpike, 0F, 0F, -0.3490659F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shaft.render(f5);
    TopRung.render(f5);
    MiddleRung.render(f5);
    BottomRung.render(f5);
    BLeftSupport.render(f5);
    BRightSupport.render(f5);
    BFrontSupport.render(f5);
    BBackSupport.render(f5);
    MLeftSupport.render(f5);
    MRightSupport.render(f5);
    MBackSupport.render(f5);
    MFrontSupport.render(f5);
    TBackSupport.render(f5);
    TFrontSupport.render(f5);
    TRightSupport.render(f5);
    TLeftSupport.render(f5);
    TopCover.render(f5);
    TopZAxis.render(f5);
    TopXAxis.render(f5);
    GreenCube.render(f5);
    BRightSpike.render(f5);
    BLeftSpike.render(f5);
    BBackSpike.render(f5);
    BFrontSpike.render(f5);
    MLeftSpike.render(f5);
    MRightSpike.render(f5);
    MBackSpike.render(f5);
    MFrontSpike.render(f5);
    TLeftSpike.render(f5);
    TRightSpike.render(f5);
    TBackSpike.render(f5);
    TFrontSpike.render(f5);
    TopFrontSpike.render(f5);
    TopBackSpike.render(f5);
    TopLeftSpike.render(f5);
    TopRightSpike.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
	}
}
