package net.minecraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLesserDemon2 extends ModelBase
{
  //fields
        ModelRenderer Hoove_Right;
        ModelRenderer Hoove_Left;
        ModelRenderer Calf_Left;
        ModelRenderer Calf_right;
        ModelRenderer Knee_Left;
        ModelRenderer Knee_Right;
        ModelRenderer Theigh_Right;
        ModelRenderer Theigh_Left;
        ModelRenderer Body_Bottom;
        ModelRenderer Body_Top;
        ModelRenderer Arm_Left;
        ModelRenderer Arm_Right;
        ModelRenderer ForeArm_Left;
        ModelRenderer ForeArm_Right;
        ModelRenderer Hand_Left;
        ModelRenderer Hand_Right;
        ModelRenderer Thumb_Left;
        ModelRenderer Thumb_Right;
        ModelRenderer Finger_Left;
        ModelRenderer Finger_right;
        ModelRenderer Pinky_Left;
        ModelRenderer Pinky_Right;
        ModelRenderer Tail;
        ModelRenderer Tail_End;
        ModelRenderer Tail_Tip;
        ModelRenderer Neck_Bottom;
        ModelRenderer Neck_Top;
        ModelRenderer Head;
        ModelRenderer Jaw;
        ModelRenderer Horn_Left_Bottom;
        ModelRenderer Horn_Right_Bottom;
        ModelRenderer Horn_Left_Top;
        ModelRenderer Horn_Right_Top;
 
  public ModelLesserDemon2()
  {
        textureWidth = 128;
        textureHeight = 64;
        
          Hoove_Right = new ModelRenderer(this, 4, 57);
          Hoove_Right.addBox(-1F, 0F, -1.5F, 2, 1, 3);
          Hoove_Right.setRotationPoint(4F, 23F, 0.5F);
          Hoove_Right.setTextureSize(128, 64);
          Hoove_Right.mirror = true;
          setRotation(Hoove_Right, 0F, 0F, 0F);
          Hoove_Left = new ModelRenderer(this, 4, 57);
          Hoove_Left.addBox(-1F, 0F, -1.5F, 2, 1, 3);
          Hoove_Left.setRotationPoint(-4F, 23F, 0.5F);
          Hoove_Left.setTextureSize(128, 64);
          Hoove_Left.mirror = true;
          setRotation(Hoove_Left, 0F, 0F, 0F);
          Calf_Left = new ModelRenderer(this, 6, 49);
          Calf_Left.addBox(-1F, 0F, -0.5F, 2, 5, 1);
          Calf_Left.setRotationPoint(-4F, 18.5F, 2.5F);
          Calf_Left.setTextureSize(128, 64);
          Calf_Left.mirror = true;
          setRotation(Calf_Left, -0.3839724F, 0F, 0F);
          Calf_right = new ModelRenderer(this, 6, 49);
          Calf_right.addBox(-1F, 0F, -0.5F, 2, 5, 1);
          Calf_right.setRotationPoint(4F, 18.5F, 2.5F);
          Calf_right.setTextureSize(128, 64);
          Calf_right.mirror = true;
          setRotation(Calf_right, -0.3839724F, 0F, 0F);
          Knee_Left = new ModelRenderer(this, 6, 42);
          Knee_Left.addBox(-1F, 0F, -0.5F, 2, 4, 1);
          Knee_Left.setRotationPoint(-4F, 15.3F, 0.9F);
          Knee_Left.setTextureSize(128, 64);
          Knee_Left.mirror = true;
          setRotation(Knee_Left, 0.4089647F, 0F, 0F);
          Knee_Right = new ModelRenderer(this, 6, 42);
          Knee_Right.addBox(-1F, 0F, -0.5F, 2, 4, 1);
          Knee_Right.setRotationPoint(4F, 15.3F, 0.9F);
          Knee_Right.setTextureSize(128, 64);
          Knee_Right.mirror = true;
          setRotation(Knee_Right, 0.4089647F, 0F, 0F);
          Theigh_Right = new ModelRenderer(this, 5, 33);
          Theigh_Right.addBox(-1F, 0F, -1F, 2, 5, 2);
          Theigh_Right.setRotationPoint(2.6F, 11F, 2.5F);
          Theigh_Right.setTextureSize(128, 64);
          Theigh_Right.mirror = true;
          setRotation(Theigh_Right, -0.296706F, 0F, -0.296706F);
          Theigh_Left = new ModelRenderer(this, 5, 33);
          Theigh_Left.addBox(-1F, 0F, -1F, 2, 5, 2);
          Theigh_Left.setRotationPoint(-2.6F, 11F, 2.5F);
          Theigh_Left.setTextureSize(128, 64);
          Theigh_Left.mirror = true;
          setRotation(Theigh_Left, -0.296706F, 0F, 0.296706F);
          Body_Bottom = new ModelRenderer(this, 75, 50);
          Body_Bottom.addBox(0F, 0F, 0F, 9, 7, 4);
          Body_Bottom.setRotationPoint(-4.6F, 4.5F, 0.5F);
          Body_Bottom.setTextureSize(128, 64);
          Body_Bottom.mirror = true;
          setRotation(Body_Bottom, 0F, 0F, 0F);
          Body_Top = new ModelRenderer(this, 72, 37);
          Body_Top.addBox(-6F, 0F, -2F, 12, 5, 5);
          Body_Top.setRotationPoint(0F, 0F, 2F);
          Body_Top.setTextureSize(128, 64);
          Body_Top.mirror = true;
          setRotation(Body_Top, 0F, 0F, 0F);
          Arm_Left = new ModelRenderer(this, 23, 25);
          Arm_Left.addBox(-1F, -1F, -1F, 2, 7, 2);
          Arm_Left.setRotationPoint(-6F, 1F, 2.5F);
          Arm_Left.setTextureSize(128, 64);
          Arm_Left.mirror = true;
          setRotation(Arm_Left, 0F, 0F, 0.3717861F);
          Arm_Right = new ModelRenderer(this, 23, 25);
          Arm_Right.addBox(-1F, -1F, -1F, 2, 7, 2);
          Arm_Right.setRotationPoint(6F, 1F, 2.5F);
          Arm_Right.setTextureSize(128, 64);
          Arm_Right.mirror = true;
          setRotation(Arm_Right, 0F, 0F, -0.37179F);
          ForeArm_Left = new ModelRenderer(this, 20, 36);
          ForeArm_Left.addBox(-2.6F, 2.6F, -10F, 1, 1, 6);
          ForeArm_Left.setRotationPoint(-6F, 1F, 2.5F);
          ForeArm_Left.setTextureSize(128, 64);
          ForeArm_Left.mirror = true;
          setRotation(ForeArm_Left, 0.8028515F, 0F, 0F);
          ForeArm_Right = new ModelRenderer(this, 20, 36);
          ForeArm_Right.addBox(1.6F, 2.6F, -10F, 1, 1, 6);
          ForeArm_Right.setRotationPoint(6F, 1F, 2.5F);
          ForeArm_Right.setTextureSize(128, 64);
          ForeArm_Right.mirror = true;
          setRotation(ForeArm_Right, 0.8028515F, 0F, 0F);
          Hand_Left = new ModelRenderer(this, 24, 45);
          Hand_Left.addBox(0F, 0F, 0F, 2, 2, 1);
          Hand_Left.setRotationPoint(-8.6F, 10F, -1.5F);
          Hand_Left.setTextureSize(128, 64);
          Hand_Left.mirror = true;
          setRotation(Hand_Left, 0F, 1.570796F, 0F);
          Hand_Right = new ModelRenderer(this, 24, 45);
          Hand_Right.addBox(0F, 0F, 0F, 2, 2, 1);
          Hand_Right.setRotationPoint(7.6F, 10F, -1.5F);
          Hand_Right.setTextureSize(128, 64);
          Hand_Right.mirror = true;
          setRotation(Hand_Right, 0F, 1.570796F, 0F);
          Thumb_Left = new ModelRenderer(this, 25, 60);
          Thumb_Left.addBox(0F, 0F, 0F, 1, 1, 1);
          Thumb_Left.setRotationPoint(-8.6F, 9.6F, -3.8F);
          Thumb_Left.setTextureSize(128, 64);
          Thumb_Left.mirror = true;
          setRotation(Thumb_Left, -0.5205006F, 0F, 0F);
          Thumb_Right = new ModelRenderer(this, 25, 60);
          Thumb_Right.addBox(0F, 0F, 0F, 1, 1, 1);
          Thumb_Right.setRotationPoint(7.6F, 9.56F, -3.8F);
          Thumb_Right.setTextureSize(128, 64);
          Thumb_Right.mirror = true;
          setRotation(Thumb_Right, -0.5205006F, 0F, 0F);
          Finger_Left = new ModelRenderer(this, 25, 55);
          Finger_Left.addBox(0F, 0F, 0F, 1, 2, 1);
          Finger_Left.setRotationPoint(-8.6F, 11.7F, -3.4F);
          Finger_Left.setTextureSize(128, 64);
          Finger_Left.mirror = true;
          setRotation(Finger_Left, -0.3171542F, 0F, 0F);
          Finger_right = new ModelRenderer(this, 25, 55);
          Finger_right.addBox(0F, 0F, 0F, 1, 2, 1);
          Finger_right.setRotationPoint(7.6F, 11.7F, -3.3F);
          Finger_right.setTextureSize(128, 64);
          Finger_right.mirror = true;
          setRotation(Finger_right, -0.3171542F, 0F, 0F);
          Pinky_Left = new ModelRenderer(this, 25, 50);
          Pinky_Left.addBox(0F, 0F, 0F, 1, 2, 1);
          Pinky_Left.setRotationPoint(-8.6F, 12F, -2.5F);
          Pinky_Left.setTextureSize(128, 64);
          Pinky_Left.mirror = true;
          setRotation(Pinky_Left, 0F, 0F, 0F);
          Pinky_Right = new ModelRenderer(this, 25, 50);
          Pinky_Right.addBox(0F, 0F, 0F, 1, 2, 1);
          Pinky_Right.setRotationPoint(7.6F, 12F, -2.5F);
          Pinky_Right.setTextureSize(128, 64);
          Pinky_Right.mirror = true;
          setRotation(Pinky_Right, 0F, 0F, 0F);
          Tail = new ModelRenderer(this, 40, 50);
          Tail.addBox(0F, 0F, 0F, 1, 1, 12);
          Tail.setRotationPoint(-0.5F, 10F, 3F);
          Tail.setTextureSize(128, 64);
          Tail.mirror = true;
          setRotation(Tail, 0.5934119F, 0F, 0F);
          Tail_End = new ModelRenderer(this, 49, 44);
          Tail_End.addBox(0F, 0F, 0F, 2, 2, 2);
          Tail_End.setRotationPoint(-1F, 2F, 12.5F);
          Tail_End.setTextureSize(128, 64);
          Tail_End.mirror = true;
          setRotation(Tail_End, -0.4363323F, 0F, 0F);
          Tail_Tip = new ModelRenderer(this, 51, 40);
          Tail_Tip.addBox(0F, 0F, 0F, 1, 1, 1);
          Tail_Tip.setRotationPoint(-0.5F, 1.7F, 13.3F);
          Tail_Tip.setTextureSize(128, 64);
          Tail_Tip.mirror = true;
          setRotation(Tail_Tip, -0.4799655F, 0F, 0F);
          Neck_Bottom = new ModelRenderer(this, 80, 30);
          Neck_Bottom.addBox(0F, 0F, 0F, 3, 3, 2);
          Neck_Bottom.setRotationPoint(-1.5F, -1.4F, 0F);
          Neck_Bottom.setTextureSize(128, 64);
          Neck_Bottom.mirror = true;
          setRotation(Neck_Bottom, 0.5934119F, 0F, 0F);
          Neck_Top = new ModelRenderer(this, 80, 24);
          Neck_Top.addBox(0F, 0F, 0F, 3, 2, 2);
          Neck_Top.setRotationPoint(-1.5F, -1.6F, -1F);
          Neck_Top.setTextureSize(128, 64);
          Neck_Top.mirror = true;
          setRotation(Neck_Top, 1.091084F, 0F, 0F);
          Head = new ModelRenderer(this, 47, 20);
          Head.addBox(0F, 0F, 0F, 5, 5, 2);
          Head.setRotationPoint(-2.5F, -3.8F, -2.2F);
          Head.setTextureSize(128, 64);
          Head.mirror = true;
          setRotation(Head, -0.0743572F, 0F, 0F);
          Jaw = new ModelRenderer(this, 49, 29);
          Jaw.addBox(0F, 0F, 0F, 4, 2, 1);
          Jaw.setRotationPoint(-2F, 0.8F, -1F);
          Jaw.setTextureSize(128, 64);
          Jaw.mirror = true;
          setRotation(Jaw, -1.07818F, 0F, 0F);
          Horn_Left_Bottom = new ModelRenderer(this, 49, 15);
          Horn_Left_Bottom.addBox(-4F, -0.5F, -0.5F, 4, 1, 1);
          Horn_Left_Bottom.setRotationPoint(-2.2F, -2.6F, -1F);
          Horn_Left_Bottom.setTextureSize(128, 64);
          Horn_Left_Bottom.mirror = true;
          setRotation(Horn_Left_Bottom, 0.2792527F, -0.3665191F, 0.2617994F);
          Horn_Right_Bottom = new ModelRenderer(this, 49, 15);
          Horn_Right_Bottom.addBox(0F, -0.5F, -0.5F, 4, 1, 1);
          Horn_Right_Bottom.setRotationPoint(2.2F, -2.6F, -1F);
          Horn_Right_Bottom.setTextureSize(128, 64);
          Horn_Right_Bottom.mirror = true;
          setRotation(Horn_Right_Bottom, 0.2792527F, 0.3665191F, -0.2617994F);
          Horn_Left_Top = new ModelRenderer(this, 52, 8);
          Horn_Left_Top.addBox(-0.5F, 0F, -0.5F, 1, 4, 1);
          Horn_Left_Top.setRotationPoint(-3.1F, -6F, -4.1F);
          Horn_Left_Top.setTextureSize(128, 64);
          Horn_Left_Top.mirror = true;
          setRotation(Horn_Left_Top, 0.7679449F, -0.4712389F, 0.4363323F);
          Horn_Right_Top = new ModelRenderer(this, 52, 8);
          Horn_Right_Top.addBox(-0.5F, 0F, -0.5F, 1, 4, 1);
          Horn_Right_Top.setRotationPoint(3.1F, -6F, -4.1F);
          Horn_Right_Top.setTextureSize(128, 64);
          Horn_Right_Top.mirror = true;
          setRotation(Horn_Right_Top, 0.7679449F, 0.4712389F, -0.4363323F);
  }
 
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Hoove_Right.renderWithRotation(f5);
        Hoove_Left.renderWithRotation(f5);
        Calf_Left.renderWithRotation(f5);
        Calf_right.renderWithRotation(f5);
        Knee_Left.renderWithRotation(f5);
        Knee_Right.renderWithRotation(f5);
        Theigh_Right.renderWithRotation(f5);
        Theigh_Left.renderWithRotation(f5);
        Body_Bottom.renderWithRotation(f5);
        Body_Top.renderWithRotation(f5);
        Arm_Left.renderWithRotation(f5);
        Arm_Right.renderWithRotation(f5);
        ForeArm_Left.renderWithRotation(f5);
        ForeArm_Right.renderWithRotation(f5);
        Hand_Left.renderWithRotation(f5);
        Hand_Right.renderWithRotation(f5);
        Thumb_Left.renderWithRotation(f5);
        Thumb_Right.renderWithRotation(f5);
        Finger_Left.renderWithRotation(f5);
        Finger_right.renderWithRotation(f5);
        Pinky_Left.renderWithRotation(f5);
        Pinky_Right.renderWithRotation(f5);
        Tail.renderWithRotation(f5);
        Tail_End.renderWithRotation(f5);
        Tail_Tip.renderWithRotation(f5);
        Neck_Bottom.renderWithRotation(f5);
        Neck_Top.renderWithRotation(f5);
        Head.renderWithRotation(f5);
        Jaw.renderWithRotation(f5);
        Horn_Left_Bottom.renderWithRotation(f5);
        Horn_Right_Bottom.renderWithRotation(f5);
        Horn_Left_Top.renderWithRotation(f5);
        Horn_Right_Top.renderWithRotation(f5);
  }
 
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
	}

}