package net.minecraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelToragHammer extends ModelBase
{
  //fields
    ModelRenderer Handle;
    ModelRenderer BottomMain;
    ModelRenderer BottomFront1;
    ModelRenderer BottomFront2;
    ModelRenderer BottomFront3;
    ModelRenderer BottomFront4;
    ModelRenderer BottomBack1;
    ModelRenderer BottomBack2;
    ModelRenderer BottomBack3;
    ModelRenderer BottomBack4;
    ModelRenderer BottomRung;
    ModelRenderer BottomSpike;
    ModelRenderer TopMain;
    ModelRenderer TopRung;
    ModelRenderer TopFront1;
    ModelRenderer TopFront2;
    ModelRenderer TopFront3;
    ModelRenderer TopFront4;
    ModelRenderer TopBack1;
    ModelRenderer TopBack2;
    ModelRenderer TopBack3;
    ModelRenderer TopBack4;
    ModelRenderer TopSpike;
    ModelRenderer BottomSpikeT;
    ModelRenderer BottomSpikeR;
    ModelRenderer BottomSpikeB;
    ModelRenderer BottomSpikeL;
    ModelRenderer TopSpikeT;
    ModelRenderer TopSpikeR;
    ModelRenderer TopSpikeB;
    ModelRenderer TopSpikeL;
  
  public ModelToragHammer()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Handle = new ModelRenderer(this, 1, 2);
      Handle.addBox(0F, 0F, 0F, 2, 33, 2);
      Handle.setRotationPoint(0F, -13F, 0F);
      Handle.setTextureSize(128, 64);
      Handle.mirror = true;
      setRotation(Handle, 0F, 0F, 0F);
      BottomMain = new ModelRenderer(this, 1, 53);
      BottomMain.addBox(0F, 0F, 0F, 5, 5, 5);
      BottomMain.setRotationPoint(-1.5F, -4F, -1.5F);
      BottomMain.setTextureSize(128, 64);
      BottomMain.mirror = true;
      setRotation(BottomMain, 0F, 0F, 0F);
      BottomFront1 = new ModelRenderer(this, 24, 59);
      BottomFront1.addBox(0F, 0F, -2F, 4, 1, 3);
      BottomFront1.setRotationPoint(-1F, -3.4F, -1.3F);
      BottomFront1.setTextureSize(128, 64);
      BottomFront1.mirror = true;
      setRotation(BottomFront1, -0.2230717F, 0F, 0F);
      BottomFront2 = new ModelRenderer(this, 24, 53);
      BottomFront2.addBox(0F, -1F, -2F, 4, 1, 3);
      BottomFront2.setRotationPoint(-1F, 0.4F, -1.3F);
      BottomFront2.setTextureSize(128, 64);
      BottomFront2.mirror = true;
      setRotation(BottomFront2, 0.2230776F, 0F, 0F);
      BottomFront3 = new ModelRenderer(this, 40, 56);
      BottomFront3.addBox(0F, 0F, 0F, 4, 4, 3);
      BottomFront3.setRotationPoint(-1F, -3.5F, -4F);
      BottomFront3.setTextureSize(128, 64);
      BottomFront3.mirror = true;
      setRotation(BottomFront3, 0F, 0F, 0F);
      BottomFront4 = new ModelRenderer(this, 56, 53);
      BottomFront4.addBox(0F, 0F, 0F, 6, 6, 4);
      BottomFront4.setRotationPoint(-2F, -4.5F, -7F);
      BottomFront4.setTextureSize(128, 64);
      BottomFront4.mirror = true;
      setRotation(BottomFront4, 0F, 0F, 0F);
      BottomBack1 = new ModelRenderer(this, 11, 1);
      BottomBack1.addBox(0F, 0F, -1F, 3, 1, 2);
      BottomBack1.setRotationPoint(-0.5F, -2.9F, 3.1F);
      BottomBack1.setTextureSize(128, 64);
      BottomBack1.mirror = true;
      setRotation(BottomBack1, 0.3346075F, 0F, 0F);
      BottomBack2 = new ModelRenderer(this, 23, 1);
      BottomBack2.addBox(0F, -1F, -1F, 3, 1, 2);
      BottomBack2.setRotationPoint(-0.5F, -0.1F, 3.1F);
      BottomBack2.setTextureSize(128, 64);
      BottomBack2.mirror = true;
      setRotation(BottomBack2, -0.3346002F, 0F, 0F);
      BottomBack3 = new ModelRenderer(this, 15, 6);
      BottomBack3.addBox(0F, 0F, 0F, 3, 3, 3);
      BottomBack3.setRotationPoint(-0.5F, -3F, 3F);
      BottomBack3.setTextureSize(128, 64);
      BottomBack3.mirror = true;
      setRotation(BottomBack3, 0F, 0F, 0F);
      BottomBack4 = new ModelRenderer(this, 14, 14);
      BottomBack4.addBox(0F, 0F, 0F, 4, 4, 3);
      BottomBack4.setRotationPoint(-1F, -3.5F, 4F);
      BottomBack4.setTextureSize(128, 64);
      BottomBack4.mirror = true;
      setRotation(BottomBack4, 0F, 0F, 0F);
      BottomRung = new ModelRenderer(this, 12, 29);
      BottomRung.addBox(0F, 0F, 0F, 3, 2, 3);
      BottomRung.setRotationPoint(-0.5F, 17F, -0.5F);
      BottomRung.setTextureSize(128, 64);
      BottomRung.mirror = true;
      setRotation(BottomRung, 0F, 0F, 0F);
      BottomSpike = new ModelRenderer(this, 26, 30);
      BottomSpike.addBox(0F, 0F, 0F, 1, 2, 1);
      BottomSpike.setRotationPoint(0.5F, 20F, 0.5F);
      BottomSpike.setTextureSize(128, 64);
      BottomSpike.mirror = true;
      setRotation(BottomSpike, 0F, 0F, 0F);
      TopMain = new ModelRenderer(this, 1, 39);
      TopMain.addBox(0F, 0F, 0F, 6, 6, 6);
      TopMain.setRotationPoint(-2F, -12F, -2F);
      TopMain.setTextureSize(128, 64);
      TopMain.mirror = true;
      setRotation(TopMain, 0F, 0F, 0F);
      TopRung = new ModelRenderer(this, 14, 22);
      TopRung.addBox(0F, 0F, 0F, 3, 2, 3);
      TopRung.setRotationPoint(-0.5F, 2F, -0.5F);
      TopRung.setTextureSize(128, 64);
      TopRung.mirror = true;
      setRotation(TopRung, 0F, 0F, 0F);
      TopFront1 = new ModelRenderer(this, 27, 45);
      TopFront1.addBox(0F, 0F, -4F, 5, 1, 5);
      TopFront1.setRotationPoint(-1.5F, -11.3F, -1.3F);
      TopFront1.setTextureSize(128, 64);
      TopFront1.mirror = true;
      setRotation(TopFront1, -0.1707118F, 0F, 0F);
      TopFront2 = new ModelRenderer(this, 27, 37);
      TopFront2.addBox(0F, -1F, -4F, 5, 1, 5);
      TopFront2.setRotationPoint(-1.5F, -6.7F, -1.3F);
      TopFront2.setTextureSize(128, 64);
      TopFront2.mirror = true;
      setRotation(TopFront2, 0.1707177F, 0F, 0F);
      TopFront3 = new ModelRenderer(this, 49, 41);
      TopFront3.addBox(0F, 0F, 0F, 5, 5, 5);
      TopFront3.setRotationPoint(-1.5F, -11.5F, -6F);
      TopFront3.setTextureSize(128, 64);
      TopFront3.mirror = true;
      setRotation(TopFront3, 0F, 0F, 0F);
      TopFront4 = new ModelRenderer(this, 71, 39);
      TopFront4.addBox(0F, 0F, 0F, 7, 7, 5);
      TopFront4.setRotationPoint(-2.5F, -12.5F, -9.5F);
      TopFront4.setTextureSize(128, 64);
      TopFront4.mirror = true;
      setRotation(TopFront4, 0F, 0F, 0F);
      TopBack1 = new ModelRenderer(this, 37, 1);
      TopBack1.addBox(0F, 0F, -1F, 4, 1, 4);
      TopBack1.setRotationPoint(-1F, -10.4F, 3.1F);
      TopBack1.setTextureSize(128, 64);
      TopBack1.mirror = true;
      setRotation(TopBack1, 0.2997009F, 0F, 0F);
      TopBack2 = new ModelRenderer(this, 56, 1);
      TopBack2.addBox(0F, -1F, -1F, 4, 1, 4);
      TopBack2.setRotationPoint(-1F, -7.6F, 3.1F);
      TopBack2.setTextureSize(128, 64);
      TopBack2.mirror = true;
      setRotation(TopBack2, -0.2996936F, 0F, 0F);
      TopBack3 = new ModelRenderer(this, 48, 8);
      TopBack3.addBox(0F, 0F, 0F, 4, 3, 3);
      TopBack3.setRotationPoint(-1F, -10.5F, 4F);
      TopBack3.setTextureSize(128, 64);
      TopBack3.mirror = true;
      setRotation(TopBack3, 0F, 0F, 0F);
      TopBack4 = new ModelRenderer(this, 46, 16);
      TopBack4.addBox(0F, 0F, 0F, 5, 5, 4);
      TopBack4.setRotationPoint(-1.5F, -11.5F, 5.5F);
      TopBack4.setTextureSize(128, 64);
      TopBack4.mirror = true;
      setRotation(TopBack4, 0F, 0F, 0F);
      TopSpike = new ModelRenderer(this, 26, 30);
      TopSpike.addBox(0F, 0F, 0F, 1, 2, 1);
      TopSpike.setRotationPoint(0.5F, -14.9F, 0.5F);
      TopSpike.setTextureSize(128, 64);
      TopSpike.mirror = true;
      setRotation(TopSpike, 0F, 0F, 0F);
      BottomSpikeT = new ModelRenderer(this, 15, 30);
      BottomSpikeT.addBox(0F, -1F, 0F, 1, 1, 2);
      BottomSpikeT.setRotationPoint(0.5F, -2.6F, 6.5F);
      BottomSpikeT.setTextureSize(128, 64);
      BottomSpikeT.mirror = true;
      setRotation(BottomSpikeT, 0.5235988F, 0F, 0F);
      BottomSpikeR = new ModelRenderer(this, 15, 30);
      BottomSpikeR.addBox(-1F, 0F, 0F, 1, 1, 2);
      BottomSpikeR.setRotationPoint(-0.1F, -2F, 6.5F);
      BottomSpikeR.setTextureSize(128, 64);
      BottomSpikeR.mirror = true;
      setRotation(BottomSpikeR, 0F, -0.5235988F, 0F);
      BottomSpikeB = new ModelRenderer(this, 15, 30);
      BottomSpikeB.addBox(0F, 0F, 0F, 1, 1, 2);
      BottomSpikeB.setRotationPoint(0.5F, -0.4F, 6.5F);
      BottomSpikeB.setTextureSize(128, 64);
      BottomSpikeB.mirror = true;
      setRotation(BottomSpikeB, -0.5235988F, 0F, 0F);
      BottomSpikeL = new ModelRenderer(this, 15, 30);
      BottomSpikeL.addBox(0F, 0F, 0F, 1, 1, 2);
      BottomSpikeL.setRotationPoint(2.1F, -2F, 6.5F);
      BottomSpikeL.setTextureSize(128, 64);
      BottomSpikeL.mirror = true;
      setRotation(BottomSpikeL, 0F, 0.5235988F, 0F);
      TopSpikeT = new ModelRenderer(this, 15, 30);
      TopSpikeT.addBox(0F, -1F, 0F, 1, 1, 2);
      TopSpikeT.setRotationPoint(0.5F, -10.6F, 9F);
      TopSpikeT.setTextureSize(128, 64);
      TopSpikeT.mirror = true;
      setRotation(TopSpikeT, 0.5235988F, 0F, 0F);
      TopSpikeR = new ModelRenderer(this, 15, 30);
      TopSpikeR.addBox(-1F, 0F, 0F, 1, 1, 2);
      TopSpikeR.setRotationPoint(-0.7F, -9.5F, 9.1F);
      TopSpikeR.setTextureSize(128, 64);
      TopSpikeR.mirror = true;
      setRotation(TopSpikeR, 0F, -0.5235988F, 0F);
      TopSpikeB = new ModelRenderer(this, 15, 30);
      TopSpikeB.addBox(0F, 0F, 0F, 1, 1, 2);
      TopSpikeB.setRotationPoint(0.5F, -7.4F, 9F);
      TopSpikeB.setTextureSize(128, 64);
      TopSpikeB.mirror = true;
      setRotation(TopSpikeB, -0.5235988F, 0F, 0F);
      TopSpikeL = new ModelRenderer(this, 15, 30);
      TopSpikeL.addBox(0F, 0F, 0F, 1, 1, 2);
      TopSpikeL.setRotationPoint(2.7F, -9.5F, 9.1F);
      TopSpikeL.setTextureSize(128, 64);
      TopSpikeL.mirror = true;
      setRotation(TopSpikeL, 0F, 0.5235988F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
	setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Handle.render(f5);
    BottomMain.render(f5);
    BottomFront1.render(f5);
    BottomFront2.render(f5);
    BottomFront3.render(f5);
    BottomFront4.render(f5);
    BottomBack1.render(f5);
    BottomBack2.render(f5);
    BottomBack3.render(f5);
    BottomBack4.render(f5);
    BottomRung.render(f5);
    BottomSpike.render(f5);
    TopMain.render(f5);
    TopRung.render(f5);
    TopFront1.render(f5);
    TopFront2.render(f5);
    TopFront3.render(f5);
    TopFront4.render(f5);
    TopBack1.render(f5);
    TopBack2.render(f5);
    TopBack3.render(f5);
    TopBack4.render(f5);
    TopSpike.render(f5);
    BottomSpikeT.render(f5);
    BottomSpikeR.render(f5);
    BottomSpikeB.render(f5);
    BottomSpikeL.render(f5);
    TopSpikeT.render(f5);
    TopSpikeR.render(f5);
    TopSpikeB.render(f5);
    TopSpikeL.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
	}
}
