package net.minecraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelStall extends ModelBase
{
  //fields
    ModelRenderer LeftFrontBottomLeg;
    ModelRenderer RightBottomLegFront;
    ModelRenderer LeftBottomLegBack;
    ModelRenderer RightBottomLegBack;
    ModelRenderer Table;
    ModelRenderer LeftStallSupportFront;
    ModelRenderer RightStallSupportFront;
    ModelRenderer LeftStallSupportBack;
    ModelRenderer RightStallSupportBack;
    ModelRenderer UpperCloth;
    ModelRenderer LowerCloth;
    ModelRenderer FishHead1;
    ModelRenderer FishTail12;
    ModelRenderer FishTail11;
    ModelRenderer FishHead2;
    ModelRenderer FishTail21;
    ModelRenderer FishTail22;
    ModelRenderer FishHead3;
    ModelRenderer FishTail31;
    ModelRenderer FishTail32;
    ModelRenderer Worm12;
    ModelRenderer Worm11;
    ModelRenderer Worm22;
    ModelRenderer Worm21;
    ModelRenderer Worm31;
    ModelRenderer Worm32;
    ModelRenderer Rod;
    ModelRenderer Reel;
    ModelRenderer Line3;
    ModelRenderer Line2;
    ModelRenderer Line1;
    ModelRenderer Bobber;
  
  public ModelStall()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      LeftFrontBottomLeg = new ModelRenderer(this, 1, 47);
      LeftFrontBottomLeg.addBox(0F, 0F, 0F, 2, 14, 2);
      LeftFrontBottomLeg.setRotationPoint(-24F, 10F, -8F);
      LeftFrontBottomLeg.setTextureSize(128, 64);
      LeftFrontBottomLeg.mirror = true;
      setRotation(LeftFrontBottomLeg, 0F, 0F, 0F);
      RightBottomLegFront = new ModelRenderer(this, 80, 47);
      RightBottomLegFront.addBox(0F, 0F, 0F, 2, 14, 2);
      RightBottomLegFront.setRotationPoint(6F, 10F, -8F);
      RightBottomLegFront.setTextureSize(128, 64);
      RightBottomLegFront.mirror = true;
      setRotation(RightBottomLegFront, 0F, 0F, 0F);
      LeftBottomLegBack = new ModelRenderer(this, 10, 47);
      LeftBottomLegBack.addBox(0F, 0F, 0F, 2, 14, 2);
      LeftBottomLegBack.setRotationPoint(-24F, 10F, 6F);
      LeftBottomLegBack.setTextureSize(128, 64);
      LeftBottomLegBack.mirror = true;
      setRotation(LeftBottomLegBack, 0F, 0F, 0F);
      RightBottomLegBack = new ModelRenderer(this, 89, 47);
      RightBottomLegBack.addBox(0F, 0F, 0F, 2, 14, 2);
      RightBottomLegBack.setRotationPoint(6F, 10F, 6F);
      RightBottomLegBack.setTextureSize(128, 64);
      RightBottomLegBack.mirror = true;
      setRotation(RightBottomLegBack, 0F, 0F, 0F);
      Table = new ModelRenderer(this, 1, 28);
      Table.addBox(0F, 0F, 0F, 32, 2, 16);
      Table.setRotationPoint(-24F, 8F, -8F);
      Table.setTextureSize(128, 64);
      Table.mirror = true;
      setRotation(Table, 0F, 0F, 0F);
      LeftStallSupportFront = new ModelRenderer(this, 2, 12);
      LeftStallSupportFront.addBox(0F, 0F, 0F, 1, 14, 1);
      LeftStallSupportFront.setRotationPoint(-23F, -6F, -7F);
      LeftStallSupportFront.setTextureSize(128, 64);
      LeftStallSupportFront.mirror = true;
      setRotation(LeftStallSupportFront, 0F, 0F, 0F);
      RightStallSupportFront = new ModelRenderer(this, 89, 12);
      RightStallSupportFront.addBox(0F, 0F, 0F, 1, 14, 1);
      RightStallSupportFront.setRotationPoint(6F, -6F, -7F);
      RightStallSupportFront.setTextureSize(128, 64);
      RightStallSupportFront.mirror = true;
      setRotation(RightStallSupportFront, 0F, 0F, 0F);
      LeftStallSupportBack = new ModelRenderer(this, 7, 16);
      LeftStallSupportBack.addBox(0F, 0F, 0F, 1, 10, 1);
      LeftStallSupportBack.setRotationPoint(-23F, -2F, 6F);
      LeftStallSupportBack.setTextureSize(128, 64);
      LeftStallSupportBack.mirror = true;
      setRotation(LeftStallSupportBack, 0F, 0F, 0F);
      RightStallSupportBack = new ModelRenderer(this, 94, 16);
      RightStallSupportBack.addBox(0F, 0F, 0F, 1, 10, 1);
      RightStallSupportBack.setRotationPoint(6F, -2F, 6F);
      RightStallSupportBack.setTextureSize(128, 64);
      RightStallSupportBack.mirror = true;
      setRotation(RightStallSupportBack, 0F, 0F, 0F);
      UpperCloth = new ModelRenderer(this, 12, 7);
      UpperCloth.addBox(0F, 0F, 0F, 30, 1, 8);
      UpperCloth.setRotationPoint(-23F, -7F, -7F);
      UpperCloth.setTextureSize(128, 64);
      UpperCloth.mirror = true;
      setRotation(UpperCloth, -0.2230717F, 0F, 0F);
      LowerCloth = new ModelRenderer(this, 12, 18);
      LowerCloth.addBox(0F, 0F, 0F, 30, 1, 8);
      LowerCloth.setRotationPoint(-23F, -5F, 0F);
      LowerCloth.setTextureSize(128, 64);
      LowerCloth.mirror = true;
      setRotation(LowerCloth, -0.3346075F, 0F, 0F);
      FishHead1 = new ModelRenderer(this, 61, 58);
      FishHead1.addBox(0F, 0F, 0F, 4, 1, 4);
      FishHead1.setRotationPoint(-1F, 7F, -5F);
      FishHead1.setTextureSize(128, 64);
      FishHead1.mirror = true;
      setRotation(FishHead1, 0F, 0F, 0F);
      FishTail12 = new ModelRenderer(this, 72, 55);
      FishTail12.addBox(0F, 0F, 0F, 1, 1, 1);
      FishTail12.setRotationPoint(3F, 7F, -2F);
      FishTail12.setTextureSize(128, 64);
      FishTail12.mirror = true;
      setRotation(FishTail12, 0F, 0F, 0F);
      FishTail11 = new ModelRenderer(this, 67, 55);
      FishTail11.addBox(0F, 0F, 0F, 1, 1, 1);
      FishTail11.setRotationPoint(2F, 7F, -1F);
      FishTail11.setTextureSize(128, 64);
      FishTail11.mirror = true;
      setRotation(FishTail11, 0F, 0F, 0F);
      FishHead2 = new ModelRenderer(this, 43, 58);
      FishHead2.addBox(0F, 0F, 0F, 4, 1, 4);
      FishHead2.setRotationPoint(-8F, 7F, -5F);
      FishHead2.setTextureSize(128, 64);
      FishHead2.mirror = true;
      setRotation(FishHead2, 0F, 0F, 0F);
      FishTail21 = new ModelRenderer(this, 50, 55);
      FishTail21.addBox(0F, 0F, 0F, 1, 1, 1);
      FishTail21.setRotationPoint(-5F, 7F, -1F);
      FishTail21.setTextureSize(128, 64);
      FishTail21.mirror = true;
      setRotation(FishTail21, 0F, 0F, 0F);
      FishTail22 = new ModelRenderer(this, 55, 55);
      FishTail22.addBox(0F, 0F, 0F, 1, 1, 1);
      FishTail22.setRotationPoint(-4F, 7F, -2F);
      FishTail22.setTextureSize(128, 64);
      FishTail22.mirror = true;
      setRotation(FishTail22, 0F, 0F, 0F);
      FishHead3 = new ModelRenderer(this, 25, 58);
      FishHead3.addBox(0F, 0F, 0F, 4, 1, 4);
      FishHead3.setRotationPoint(-15F, 7F, -5F);
      FishHead3.setTextureSize(128, 64);
      FishHead3.mirror = true;
      setRotation(FishHead3, 0F, 0F, 0F);
      FishTail31 = new ModelRenderer(this, 33, 55);
      FishTail31.addBox(0F, 0F, 0F, 1, 1, 1);
      FishTail31.setRotationPoint(-12F, 7F, -1F);
      FishTail31.setTextureSize(128, 64);
      FishTail31.mirror = true;
      setRotation(FishTail31, 0F, 0F, 0F);
      FishTail32 = new ModelRenderer(this, 38, 55);
      FishTail32.addBox(0F, 0F, 0F, 1, 1, 1);
      FishTail32.setRotationPoint(-11F, 7F, -2F);
      FishTail32.setTextureSize(128, 64);
      FishTail32.mirror = true;
      setRotation(FishTail32, 0F, 0F, 0F);
      Worm12 = new ModelRenderer(this, 28, 48);
      Worm12.addBox(0F, 0F, 0F, 1, 1, 3);
      Worm12.setRotationPoint(-21F, 7F, -2F);
      Worm12.setTextureSize(128, 64);
      Worm12.mirror = true;
      setRotation(Worm12, 0F, 0F, 0F);
      Worm11 = new ModelRenderer(this, 19, 50);
      Worm11.addBox(0F, 0F, 0F, 1, 1, 3);
      Worm11.setRotationPoint(-22F, 7F, -4F);
      Worm11.setTextureSize(128, 64);
      Worm11.mirror = true;
      setRotation(Worm11, 0F, 0F, 0F);
      Worm22 = new ModelRenderer(this, 50, 48);
      Worm22.addBox(0F, 0F, 0F, 1, 1, 3);
      Worm22.setRotationPoint(-18F, 7F, 0F);
      Worm22.setTextureSize(128, 64);
      Worm22.mirror = true;
      setRotation(Worm22, 0F, 0F, 0F);
      Worm21 = new ModelRenderer(this, 41, 50);
      Worm21.addBox(0F, 0F, 0F, 1, 1, 3);
      Worm21.setRotationPoint(-17F, 7F, -2F);
      Worm21.setTextureSize(128, 64);
      Worm21.mirror = true;
      setRotation(Worm21, 0F, 0F, 0F);
      Worm31 = new ModelRenderer(this, 61, 51);
      Worm31.addBox(0F, 0F, 0F, 3, 1, 1);
      Worm31.setRotationPoint(-22F, 7F, 4F);
      Worm31.setTextureSize(128, 64);
      Worm31.mirror = true;
      setRotation(Worm31, 0F, 0F, 0F);
      Worm32 = new ModelRenderer(this, 67, 48);
      Worm32.addBox(0F, 0F, 0F, 3, 1, 1);
      Worm32.setRotationPoint(-20F, 7F, 5F);
      Worm32.setTextureSize(128, 64);
      Worm32.mirror = true;
      setRotation(Worm32, 0F, 0F, 0F);
      Rod = new ModelRenderer(this, 28, 0);
      Rod.addBox(0F, 0F, 0F, 12, 1, 1);
      Rod.setRotationPoint(-11F, 7F, 4F);
      Rod.setTextureSize(128, 64);
      Rod.mirror = true;
      setRotation(Rod, 0F, -0.1115358F, 0F);
      Reel = new ModelRenderer(this, 30, 3);
      Reel.addBox(0F, 0F, 0F, 2, 1, 1);
      Reel.setRotationPoint(-10F, 7F, 3F);
      Reel.setTextureSize(128, 64);
      Reel.mirror = true;
      setRotation(Reel, 0F, -0.111544F, 0F);
      Line3 = new ModelRenderer(this, 61, 4);
      Line3.addBox(0F, 0F, 0F, 1, 1, 1);
      Line3.setRotationPoint(0F, 7F, 4F);
      Line3.setTextureSize(128, 64);
      Line3.mirror = true;
      setRotation(Line3, 0F, -0.2974289F, 0F);
      Line2 = new ModelRenderer(this, 52, 4);
      Line2.addBox(0F, 0F, 0F, 3, 1, 1);
      Line2.setRotationPoint(-2.7F, 7F, 2.3F);
      Line2.setTextureSize(128, 64);
      Line2.mirror = true;
      setRotation(Line2, 0F, -0.2974289F, 0F);
      Line1 = new ModelRenderer(this, 45, 4);
      Line1.addBox(0F, 0F, 0F, 2, 1, 1);
      Line1.setRotationPoint(-4.7F, 7F, 1.3F);
      Line1.setTextureSize(128, 64);
      Line1.mirror = true;
      setRotation(Line1, 0F, -0.1487144F, 0F);
      Bobber = new ModelRenderer(this, 40, 4);
      Bobber.addBox(0F, 0F, 0F, 1, 1, 1);
      Bobber.setRotationPoint(-5.8F, 7F, 2.3F);
      Bobber.setTextureSize(128, 64);
      Bobber.mirror = true;
      setRotation(Bobber, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
	setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    LeftFrontBottomLeg.render(f5);
    RightBottomLegFront.render(f5);
    LeftBottomLegBack.render(f5);
    RightBottomLegBack.render(f5);
    Table.render(f5);
    LeftStallSupportFront.render(f5);
    RightStallSupportFront.render(f5);
    LeftStallSupportBack.render(f5);
    RightStallSupportBack.render(f5);
    UpperCloth.render(f5);
    LowerCloth.render(f5);
    FishHead1.render(f5);
    FishTail12.render(f5);
    FishTail11.render(f5);
    FishHead2.render(f5);
    FishTail21.render(f5);
    FishTail22.render(f5);
    FishHead3.render(f5);
    FishTail31.render(f5);
    FishTail32.render(f5);
    Worm12.render(f5);
    Worm11.render(f5);
    Worm22.render(f5);
    Worm21.render(f5);
    Worm31.render(f5);
    Worm32.render(f5);
    Rod.render(f5);
    Reel.render(f5);
    Line3.render(f5);
    Line2.render(f5);
    Line1.render(f5);
    Bobber.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent)
 	{
 		super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
 	}

}
